In [2]:
import pandas as pd
import os

dataset = 'GHCNh'
station_file = os.path.join(f"../../../data/point_data/{dataset}", "summaries", "stations_summary.csv")
station_file = '../data/point_data/GHCNh/summaries/stations_summary.csv'
station_file = 'wrf_tools/data/ghcnh-station-list.csv'
station_df = pd.read_csv(station_file)
station_df

,GHCN_ID,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,GSN,(US)HCN_(US)CRN,WMO_ID,ICAO
0,AAI0000TNCA,12.5014,-70.0152,18.3,NaN,REINA BEATRIX INTL,NaN,NaN,NaN,NaN
1,ACL000BARA9,17.5910,-61.8210,5.0,TX,BARBUDA,NaN,NaN,NaN,NaN
2,ACM00078861,17.1167,-61.7833,10.0,NaN,COOLIDGE FIELD ANTIGUA (AUX.,NaN,NaN,NaN,NaN
3,ACU55-00189,18.6000,-63.4700,10.0,NaN,SOMBRERO,NaN,NaN,NaN,NaN
4,ACU55-00190,18.6000,-63.4700,12.0,NaN,SOMBRERO,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
34176,ZIM00067967,-21.3833,28.9833,770.0,NaN,TULI,NaN,NaN,NaN,NaN
34177,ZIM00067974,-19.8333,30.7833,-999.9,NaN,MAKOHOLI,NaN,NaN,NaN,NaN
34178,ZIM00067976,-20.5500,31.0833,700.0,NaN,RUPIKE,NaN,NaN,NaN,NaN
34179,ZIM00067979,-20.3333,31.4667,770.0,NaN,ZAKA,NaN,NaN,NaN,NaN
34180,ZIM00067989,-20.4170,32.3170,442.0,NaN,RUPISI,NaN,NaN,NaN,NaN

In [16]:

pd.set_option("display.max_columns", None) 
df = pd.read_csv('../data/point_data/GHCNh/GHCNh_THI0000VTBD_2025.psv', index_col=2, parse_dates=True, sep="|")

df

/tmp/ipykernel_450305/4291884568.py:2: DtypeWarning: Columns (49,51,53,72,73,75,77,211,213,215) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/point_data/GHCNh/GHCNh_THI0000VTBD_2025.psv', index_col=2, parse_dates=True, sep="|")

,STATION,Station_name,LATITUDE,LONGITUDE,Elevation,temperature,temperature_Measurement_Code,temperature_Quality_Code,temperature_Report_Type,temperature_Source_Code,temperature_Source_Station_ID,dew_point_temperature,dew_point_temperature_Measurement_Code,dew_point_temperature_Quality_Code,dew_point_temperature_Report_Type,dew_point_temperature_Source_Code,dew_point_temperature_Source_Station_ID,station_level_pressure,station_level_pressure_Measurement_Code,station_level_pressure_Quality_Code,station_level_pressure_Report_Type,station_level_pressure_Source_Code,station_level_pressure_Source_Station_ID,sea_level_pressure,sea_level_pressure_Measurement_Code,sea_level_pressure_Quality_Code,sea_level_pressure_Report_Type,sea_level_pressure_Source_Code,sea_level_pressure_Source_Station_ID,wind_direction,wind_direction_Measurement_Code,wind_direction_Quality_Code,wind_direction_Report_Type,wind_direction_Source_Code,wind_direction_Source_Station_ID,wind_speed,wind_speed_Measurement_Code,wind_speed_Quality_Code,wind_speed_Report_Type,wind_speed_Source_Code,wind_speed_Source_Station_ID,wind_gust,wind_gust_Measurement_Code,wind_gust_Quality_Code,wind_gust_Report_Type,wind_gust_Source_Code,wind_gust_Source_Station_ID,precipitation,precipitation_Measurement_Code,precipitation_Quality_Code,precipitation_Report_Type,precipitation_Source_Code,precipitation_Source_Station_ID,relative_humidity,relative_humidity_Measurement_Code,relative_humidity_Quality_Code,relative_humidity_Report_Type,relative_humidity_Source_Code,relative_humidity_Source_Station_ID,wet_bulb_temperature,wet_bulb_temperature_Measurement_Code,wet_bulb_temperature_Quality_Code,wet_bulb_temperature_Report_Type,wet_bulb_temperature_Source_Code,wet_bulb_temperature_Source_Station_ID,pres_wx_MW1,pres_wx_MW1_Measurement_Code,pres_wx_MW1_Quality_Code,pres_wx_MW1_Report_Type,pres_wx_MW1_Source_Code,pres_wx_MW1_Source_Station_ID,pres_wx_MW2,pres_wx_MW2_Measurement_Code,pres_wx_MW2_Quality_Code,pres_wx_MW2_Report_Type,pres_wx_MW2_Source_Code,pres_wx_MW2_Source_Station_ID,pres_wx_MW3,pres_wx_MW3_Measurement_Code,pres_wx_MW3_Quality_Code,pres_wx_MW3_Report_Type,pres_wx_MW3_Source_Code,pres_wx_MW3_Source_Station_ID,pres_wx_AU1,pres_wx_AU1_Measurement_Code,pres_wx_AU1_Quality_Code,pres_wx_AU1_Report_Type,pres_wx_AU1_Source_Code,pres_wx_AU1_Source_Station_ID,pres_wx_AU2,pres_wx_AU2_Measurement_Code,pres_wx_AU2_Quality_Code,pres_wx_AU2_Report_Type,pres_wx_AU2_Source_Code,pres_wx_AU2_Source_Station_ID,pres_wx_AU3,pres_wx_AU3_Measurement_Code,pres_wx_AU3_Quality_Code,pres_wx_AU3_Report_Type,pres_wx_AU3_Source_Code,pres_wx_AU3_Source_Station_ID,pres_wx_AW1,pres_wx_AW1_Measurement_Code,pres_wx_AW1_Quality_Code,pres_wx_AW1_Report_Type,pres_wx_AW1_Source_Code,pres_wx_AW1_Source_Station_ID,pres_wx_AW2,pres_wx_AW2_Measurement_Code,pres_wx_AW2_Quality_Code,pres_wx_AW2_Report_Type,pres_wx_AW2_Source_Code,pres_wx_AW2_Source_Station_ID,pres_wx_AW3,pres_wx_AW3_Measurement_Code,pres_wx_AW3_Quality_Code,pres_wx_AW3_Report_Type,pres_wx_AW3_Source_Code,pres_wx_AW3_Source_Station_ID,snow_depth,snow_depth_Measurement_Code,snow_depth_Quality_Code,snow_depth_Report_Type,snow_depth_Source_Code,snow_depth_Source_Station_ID,visibility,visibility_Measurement_Code,visibility_Quality_Code,visibility_Report_Type,visibility_Source_Code,visibility_Source_Station_ID,altimeter,altimeter_Measurement_Code,altimeter_Quality_Code,altimeter_Report_Type,altimeter_Source_Code,altimeter_Source_Station_ID,pressure_3hr_change,pressure_3hr_change_Measurement_Code,pressure_3hr_change_Quality_Code,pressure_3hr_change_Report_Type,pressure_3hr_change_Source_Code,pressure_3hr_change_Source_Station_ID,sky_cover_1,sky_cover_1_Measurement_Code,sky_cover_1_Quality_Code,sky_cover_1_Report_Type,sky_cover_1_Source_Code,sky_cover_1_Source_Station_ID,sky_cover_baseht_1,sky_cover_baseht_1_Measurement_Code,sky_cover_baseht_1_Quality_Code,sky_cover_baseht_1_Report_Type,sky_cover_baseht_1_Source_Code,sky_cover_baseht_1_Source_Station_ID,sky_cover_2,sky_cover_2_Measurement_Code,sky_cover_2_Quality_Code,sky_cover_2_Report_Type,sky_cover_2_Source_Code,sky_cover_2_Source_Station_ID,sky_cover_baseht_2,sky_cover_baseht_2_Measurement_Code,sky_cover_baseht_2_Quality_Code,sky_cover_baseht_2_Report_Type,sky_cover_baseht_2_Source_Code,sky_cover_baseht_2_Source_Station_ID,sky_cover_3,sky_cover_3_Measurement_Code,sky_cover_3_Quality_Code,sky_cover_3_Report_Type,sky_cover_3_Source_Code,sky_cover_3_Source_Station_ID,sky_cover_baseht_3,sky_cover_baseht_3_Measurement_Code,sky_cover_baseht_3_Quality_Code,sky_cover_baseht_3_Report_Type,sky_cover_baseht_3_Source_Code,sky_cover_baseht_3_Source_Station_ID,precipitation_3_hour,precipitation_3_hour_Measurement_Code,precipitation_3_hour_Quality_Code,precipitation_3_hour_Report_Type,precipitation_3_hour_Source_Code,precipitation_3_hour_Source_Station_ID,precipitation_6_hour,precipitation_6_hour_Measurement_Code,precipitation_6_hour_Quality_Code,precipitation_6_hour_Report_Type,precipitation_6_hour_Source_Code,precipitation_6_hour_Source_Station_ID,precipitation_9_hour,precipitation_9_hour_Measurement_Code,precipitation_9_hour_Quality_Code,precipitation_9_hour_Report_Type,precipitation_9_hour_Source_Code,precipitation_9_hour_Source_Station_ID,precipitation_12_hour,precipitation_12_hour_Measurement_Code,precipitation_12_hour_Quality_Code,precipitation_12_hour_Report_Type,precipitation_12_hour_Source_Code,precipitation_12_hour_Source_Station_ID,precipitation_15_hour,precipitation_15_hour_Measurement_Code,precipitation_15_hour_Quality_Code,precipitation_15_hour_Report_Type,precipitation_15_hour_Source_Code,precipitation_15_hour_Source_Station_ID,precipitation_18_hour,precipitation_18_hour_Measurement_Code,precipitation_18_hour_Quality_Code,precipitation_18_hour_Report_Type,precipitation_18_hour_Source_Code,precipitation_18_hour_Source_Station_ID,precipitation_21_hour,precipitation_21_hour_Measurement_Code,precipitation_21_hour_Quality_Code,precipitation_21_hour_Report_Type,precipitation_21_hour_Source_Code,precipitation_21_hour_Source_Station_ID,precipitation_24_hour,precipitation_24_hour_Measurement_Code,precipitation_24_hour_Quality_Code,precipitation_24_hour_Report_Type,precipitation_24_hour_Source_Code,precipitation_24_hour_Source_Station_ID,remarks,remarks_Measurement_Code,remarks_Quality_Code,remarks_Report_Type,remarks_Source_Code,remarks_Source_Station_ID
DATE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,22.0,NaN,1,FM15-METAR,223,ICAO-VTBD,16.0,NaN,1,FM15-METAR,223,ICAO-VTBD,1011.9,NaN,1.0,FM12-SYNOP,223.0,ICAO-VTBD,1013.3,NaN,1.0,FM12-SYNOP,223.0,ICAO-VTBD,999.0,C-Calm,NaN,FM15-METAR,223,ICAO-VTBD,0.0,C-Calm,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,18.0,Derived,NaN,FM12-SYNOP,223.0,ICAO-VTBD,BR:10,BR:10-Mist,1.0,FM12-SYNOP,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1013.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,1.2,2-Incr-(st,1.0,FM12-SYNOP,223.0,ICAO-VTBD,FEW:01,01-One-okt,1.0,FM12-SYNOP,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET054METAR VTBD 010000Z 00000KT 9000 NSC 22/1...,NaN,F,NaN,223,ICAO-VTBD
2025-01-01 00:30:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,22.0,NaN,1,FM15-METAR,223,ICAO-VTBD,16.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,999.0,V-Variable,NaN,FM15-METAR,223,ICAO-VTBD,0.5,V-Variable,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1013.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET054METAR VTBD 010030Z VRB01KT 9000 NSC 22/1...,NaN,F,NaN,223,ICAO-VTBD
2025-01-01 01:00:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,24.0,NaN,1,FM15-METAR,223,ICAO-VTBD,16.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,V-Variable,1.0,FM15-METAR,223,ICAO-VTBD,1.5,V-Variable,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1014.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET062METAR VTBD 010100Z 05003KT 020V090 9000 ...,NaN,F,NaN,223,ICAO-VTBD
2025-01-01 01:30:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,25.0,NaN,1,FM15-METAR,223,ICAO-VTBD,16.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,V-Variable,1.0,FM15-METAR,223,ICAO-VTBD,1.5,V-Variable,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1014.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET062METAR VTBD 010130Z 04003KT 360V120 9000 ...,NaN,F,NaN,223,ICAO-VTBD
2025-01-01 02:00:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,26.0,NaN,1,FM15-METAR,223,ICAO-VTBD,16.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,999.0,V-Variable,NaN,FM15-METAR,223,ICAO-VTBD,1.0,V-Variable,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1014.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET054METAR VTBD 010200Z VRB02KT 9000 NSC 26/1...,NaN,F,NaN,223,ICAO-VTBD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-03 19:30:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,29.0,NaN,1,FM15-METAR,223,ICAO-VTBD,24.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190.0,N-Normal,1.0,FM15-METAR,223,ICAO-VTBD,3.1,N-Normal,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1010.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,FEW:02,02-Two-okt,1.0,FM15-METAR,223.0,ICAO-VTBD,610.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET057METAR VTBD 031930Z 19006KT 9999 FEW020 2...,NaN,F,NaN,223,ICAO-VTBD
2025-04-03 20:00:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,28.0,NaN,1,FM15-METAR,223,ICAO-VTBD,24.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190.0,N-Normal,1.0,FM15-METAR,223,ICAO-VTBD,2.6,N-Normal,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1010.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,FEW:02,02-Two-okt,1.0,FM15-METAR,223.0,ICAO-VTBD,610.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET057METAR VTBD 032000Z 19005KT 9999 FEW020 2...,NaN,F,NaN,223,ICAO-VTBD
2025-04-03 20:30:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,28.0,NaN,1,FM15-METAR,223,ICAO-VTBD,24.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190.0,N-Normal,1.0,FM15-METAR,223,ICAO-VTBD,2.6,N-Normal,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1010.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,FEW:02,02-Two-okt,1.0,FM15-METAR,223.0,ICAO-VTBD,610.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET057METAR VTBD 032030Z 19005KT 9999 FEW020 2...,NaN,F,NaN,223,ICAO-VTBD
2025-04-03 21:00:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,28.0,NaN,1,FM15-METAR,223,ICAO-VTBD,24.0,NaN,1,FM15-METAR,223,ICAO-VTBD,1008.4,NaN,1.0,FM12-SYNOP,223.0,ICAO-VTBD,1009.8,NaN,1.0,FM12-SYNOP,223.0,ICAO-VTBD,170.0,V-Variable,1.0,FM15-METAR,223,ICAO-VTBD,1.5,V-Variable,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,25.0,Derived,NaN,FM12-SYNOP,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1010.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,-1.6,7-Decr-(st,1.0,FM12-SYNOP,223.0,ICAO-VTBD,FEW:02,02-Two-okt,1.0,FM15-METAR,223.0,ICAO-VTBD,610.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET065METAR VTBD 032100Z 17003KT 120V200 9999 ...,NaN,F,NaN,223,ICAO-VTBD
2025-04-03 21:30:00,THI0000VTBD,BANGKOK INTL,13.9126,100.6068,2.7,28.0,NaN,1,FM15-METAR,223,ICAO-VTBD,24.0,NaN,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.0,N-Normal,1.0,FM15-METAR,223,ICAO-VTBD,1.5,N-Normal,1,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,Derived,NaN,FM15-METAR,223,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999,P-Prevaili,1,FM15-METAR,223,ICAO-VTBD,1010.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,FEW:02,02-Two-okt,1.0,FM15-METAR,223.0,ICAO-VTBD,610.0,NaN,1.0,FM15-METAR,223.0,ICAO-VTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET057METAR VTBD 032130Z 20003KT 9999 FEW020 2...,NaN,F,NaN,223,ICAO-VTBD